version: '3.9'

services:
  bot-server:
    build: ./bot
    ports:
      - "50051:50051"
    networks:
      - grpc-net

  node-client:
    build: ./server
    depends_on:
      - bot-server
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge
